<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>airbnbanalysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="AirbnbAnalysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="AirbnbAnalysis_files/libs/quarto-html/quarto.js"></script>
<script src="AirbnbAnalysis_files/libs/quarto-html/popper.min.js"></script>
<script src="AirbnbAnalysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="AirbnbAnalysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="AirbnbAnalysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="AirbnbAnalysis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="AirbnbAnalysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="AirbnbAnalysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="AirbnbAnalysis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Cargar la fuente de datos</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar los datos del dataframe airbnb</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>airbnb <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'data/airbnb.csv'</span>, <span class="at">sep=</span><span class="st">','</span>, <span class="at">stringsAsFactors =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Explorando los datos</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar las primeras 6 filas del dataframe</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb, <span class="at">n =</span> <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Zipcode Neighbourhood.Cleansed Property.Type       Room.Type Accommodates
1   28004            Universidad     Apartment    Private room            2
2   28004            Universidad     Apartment Entire home/apt            6
3   28004            Universidad     Apartment Entire home/apt            3
4   28004            Universidad          Loft Entire home/apt            3
5   28015            Universidad     Apartment Entire home/apt            5
6   28004            Universidad     Apartment Entire home/apt            2
  Bathrooms Bedrooms Beds Bed.Type
1         2        1    1 Real Bed
2         1        3    5 Real Bed
3         1        2    2 Real Bed
4         2        1    1 Real Bed
5         1        1    1 Real Bed
6         1        0    1 Real Bed
                                                                                                                                                                                                                                                                                                                                                         Amenities
1                                                                                                                                                                              TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron
2                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  Square.Feet Price Review.Scores.Rating
1          NA    35                   NA
2          NA    92                   96
3          NA    55                   91
4          NA    60                  100
5         538    75                   90
6          NA    55                   95</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Descripción detallada del df</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   13207 obs. of  13 variables:
 $ Zipcode               : Factor w/ 77 levels "","-","20013",..: 15 15 15 15 26 15 15 15 26 15 ...
 $ Neighbourhood.Cleansed: Factor w/ 125 levels "Abrantes","Acacias",..: 115 115 115 115 115 115 115 115 115 115 ...
 $ Property.Type         : Factor w/ 22 levels "Apartment","Bed &amp; Breakfast",..: 1 1 1 16 1 1 15 1 1 1 ...
 $ Room.Type             : Factor w/ 3 levels "Entire home/apt",..: 2 1 1 1 1 1 2 1 1 1 ...
 $ Accommodates          : int  2 6 3 3 5 2 7 3 2 4 ...
 $ Bathrooms             : num  2 1 1 2 1 1 5 1 1 2 ...
 $ Bedrooms              : int  1 3 2 1 1 0 1 1 1 2 ...
 $ Beds                  : int  1 5 2 1 1 1 7 NA 1 2 ...
 $ Bed.Type              : Factor w/ 5 levels "Airbed","Couch",..: 5 5 5 5 5 5 5 5 5 5 ...
 $ Amenities             : Factor w/ 11073 levels "","Air conditioning,Breakfast,Washer,Essentials,Hair dryer",..: 9444 4020 3249 4039 8369 2047 961 7436 5618 7736 ...
 $ Square.Feet           : int  NA NA NA NA 538 NA NA NA 700 NA ...
 $ Price                 : int  35 92 55 60 75 55 60 70 90 155 ...
 $ Review.Scores.Rating  : int  NA 96 91 100 90 95 77 84 98 NA ...</code></pre>
</div>
</div>
<p><strong>Renombrar las columnas de la siguiente forma:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Nombre original</th>
<th>Nuevo nombre</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Zipcode</td>
<td>CodigoPostal</td>
</tr>
<tr class="even">
<td>Neighbourhood.Cleansed</td>
<td>Barrio</td>
</tr>
<tr class="odd">
<td>Property.Type</td>
<td>TipoPropiedad</td>
</tr>
<tr class="even">
<td>Room.Type</td>
<td>TipoAlquiler</td>
</tr>
<tr class="odd">
<td>Accommodates</td>
<td>MaxOcupantes</td>
</tr>
<tr class="even">
<td>Bathrooms</td>
<td>NumBanyos</td>
</tr>
<tr class="odd">
<td>Bedrooms</td>
<td>NumDormitorios</td>
</tr>
<tr class="even">
<td>Beds</td>
<td>NumCamas</td>
</tr>
<tr class="odd">
<td>Bed.Type</td>
<td>TipoCama</td>
</tr>
<tr class="even">
<td>Amenities</td>
<td>Comodidades</td>
</tr>
<tr class="odd">
<td>Square.Feet</td>
<td>PiesCuadrados</td>
</tr>
<tr class="even">
<td>Price</td>
<td>Precio</td>
</tr>
<tr class="odd">
<td>Review.Scores.Rating</td>
<td>Puntuacion</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(airbnb) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"CodigoPostal"</span>, <span class="st">"Barrio"</span>, <span class="st">"TipoPropiedad"</span>, <span class="st">"TipoAlquiler"</span>, <span class="st">"MaxOcupantes"</span>, <span class="st">"NumBanyos"</span>, <span class="st">"NumDormitorios"</span>, <span class="st">"NumCamas"</span>, <span class="st">"TipoCama"</span>, <span class="st">"Comodidades"</span>, <span class="st">"PiesCuadrados"</span>, <span class="st">"Precio"</span>, <span class="st">"Puntuacion"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Queremos cambiar todos los nombres de las columnas, por lo que el método para renombrar es asignar un nuevo vector de nombres a la propiedad <code>names()</code> del dataframe.</p>
<p>Si solo hubiéramos querido cambiar el nombre de algunas columnas, podríamos haberlo hecho de la siguiente manera:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># names(airbnb)[1] &lt;- "nueva_col1"</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># names(airbnb)[2] &lt;- "nueva_col2"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Vamos a verificar el cambio:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  CodigoPostal      Barrio TipoPropiedad    TipoAlquiler MaxOcupantes NumBanyos
1        28004 Universidad     Apartment    Private room            2         2
2        28004 Universidad     Apartment Entire home/apt            6         1
3        28004 Universidad     Apartment Entire home/apt            3         1
4        28004 Universidad          Loft Entire home/apt            3         2
5        28015 Universidad     Apartment Entire home/apt            5         1
  NumDormitorios NumCamas TipoCama
1              1        1 Real Bed
2              3        5 Real Bed
3              2        2 Real Bed
4              1        1 Real Bed
5              1        1 Real Bed
                                                                                                                                                                                                                                                                                                             Comodidades
1                                                                                                                                    TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron
2                                                                                                                                            TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                 TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4 TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                     TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
  PiesCuadrados Precio Puntuacion
1            NA     35         NA
2            NA     92         96
3            NA     55         91
4            NA     60        100
5           538     75         90</code></pre>
</div>
</div>
<hr>
<p><strong>1. Crea una nueva columna llamada <code>MetrosCuadrados</code> a partir de la columna <code>PiesCuadrados</code></strong></p>
<p>1 pie cuadrado son 0,092903 metros cuadrados</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>MetrosCuadrados <span class="ot">&lt;-</span> airbnb<span class="sc">$</span>PiesCuadrados <span class="sc">*</span> <span class="fl">0.092903</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los 6 primeros registros, verificar la operación</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb, <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  CodigoPostal      Barrio TipoPropiedad    TipoAlquiler MaxOcupantes NumBanyos
1        28004 Universidad     Apartment    Private room            2         2
2        28004 Universidad     Apartment Entire home/apt            6         1
3        28004 Universidad     Apartment Entire home/apt            3         1
4        28004 Universidad          Loft Entire home/apt            3         2
5        28015 Universidad     Apartment Entire home/apt            5         1
6        28004 Universidad     Apartment Entire home/apt            2         1
  NumDormitorios NumCamas TipoCama
1              1        1 Real Bed
2              3        5 Real Bed
3              2        2 Real Bed
4              1        1 Real Bed
5              1        1 Real Bed
6              0        1 Real Bed
                                                                                                                                                                                                                                                                                                                                                       Comodidades
1                                                                                                                                                                              TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron
2                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  PiesCuadrados Precio Puntuacion MetrosCuadrados
1            NA     35         NA              NA
2            NA     92         96              NA
3            NA     55         91              NA
4            NA     60        100              NA
5           538     75         90        49.98181
6            NA     55         95              NA</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Muestra los metros cuadrados de los 10 primeros registros</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb<span class="sc">$</span>MetrosCuadrados, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]       NA       NA       NA       NA 49.98181       NA       NA       NA
 [9] 65.03210       NA</code></pre>
</div>
</div>
<hr>
<p><strong>2. Miremos el código postal</strong></p>
<p>Es una variable con entradas erróneas. Hay valores como ’‘,’-’ y ‘28’ que deberían ser considerados como NA. Así mismo también debería ser NA todos los que no comiencen por 28, ya que estamos con códigos postales de Madrid.</p>
<p>El código postal 28002, 28004 y 28051 tienen entradas repetidas. Por ejemplo las entradas 28002 deberían ir dentro de 28002.</p>
<p>El código 2804 debería ser 28004, 2805 debería ser 28005 y 2815 junto con 2815 debería ser 28015.</p>
<p><strong>Limpia los datos de la columna Codigo Postal.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Veamos los valores únicos de la columna CodigoPostal</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>valores_unicos_cod_postal <span class="ot">&lt;-</span> <span class="fu">unique</span>(airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(valores_unicos_cod_postal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 28004        28015        28013        28005        28012       
 [6] 28014        28045        27013                     28007       
[11] 28028        28009        28001        28006        28010       
[16] 28002        28034        28050        28008        28011       
[21] 28049        28038        28053        28047        28025       
[26] 28019        28024        28016        28036        28046       
[31] 28039        28020        28003        28029        28054       
[36] 28041        28026        28058        28018        28030       
[41] 28017        28027        28043        28033        28055       
[46] 28021        28032        28037        28022        28042       
[51] 28094        280013       28002\n28002 28035        28040       
[56] 28031        28044        28105        28023        2805        
[61] 28051        Madrid 28004 20126        28051\n28051 28850       
[66] 28048        28056        20013        27004        28060       
[71] -            28           2815         25008        2015        
[76] 28052        2804        
77 Levels:  - 20013 20126 2015 25008 27004 27013 28 28001 280013 ... Madrid 28004</code></pre>
</div>
</div>
<p><strong>Cargamos la librería <code>dplyr</code> para facilitar las manipulaciones</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Limpieza de la columna CodigoPostal</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>airbnb <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CodigoPostal =</span> <span class="fu">as.character</span>(CodigoPostal)) <span class="sc">%&gt;%</span>  <span class="co"># Convertir a caracter</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CodigoPostal =</span> <span class="fu">ifelse</span>(CodigoPostal <span class="sc">==</span> <span class="st">''</span> <span class="sc">|</span> </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>                        CodigoPostal <span class="sc">==</span> <span class="st">'-'</span> <span class="sc">|</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>                        CodigoPostal <span class="sc">==</span> <span class="st">'28'</span> <span class="sc">|</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>                        <span class="sc">!</span><span class="fu">startsWith</span>(CodigoPostal, <span class="st">'28'</span>), </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>                        <span class="cn">NA</span>, CodigoPostal)) <span class="sc">%&gt;%</span>  <span class="co"># Tratar valores erróneos y no válidos</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CodigoPostal =</span> <span class="fu">gsub</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">.*"</span>, <span class="st">""</span>, CodigoPostal)) <span class="sc">%&gt;%</span>  <span class="co"># Quitar entradas repetidas</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CodigoPostal =</span> <span class="fu">case_when</span>(</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    CodigoPostal <span class="sc">==</span> <span class="st">"2804"</span> <span class="sc">~</span> <span class="st">"28004"</span>,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    CodigoPostal <span class="sc">==</span> <span class="st">"2805"</span> <span class="sc">~</span> <span class="st">"28005"</span>,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    CodigoPostal <span class="sc">==</span> <span class="st">"2815"</span> <span class="sc">~</span> <span class="st">"28015"</span>,</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> CodigoPostal</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>  ))  <span class="co"># Corregir códigos postales incorrectos</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La función <code>mutate()</code> en R, que forma parte del paquete <code>dplyr</code>, se utiliza para crear nuevas columnas o modificar columnas existentes en un dataframe. Es una de las funciones clave en dplyr para la manipulación de datos.</p>
<p>Usamos <code>ifelse()</code> y <code>case_when()</code> dentro de <code>mutate()</code>para realizar cambios condicionales más complejos.</p>
<p>El operador de tubería (“pipe operator”) <code>%&gt;%</code> facilita la lectura y escritura de código al encadenar múltiples funciones en una secuencia de operaciones. Permite encadenar operaciones como filtrado, selección, agrupación y resumen de manera intuitiva.</p>
<hr>
<p><strong>3. Una vez limpios los datos ¿Cuáles son los códigos postales que tenemos?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>valores_unicos_cod_postal_limpios <span class="ot">&lt;-</span> <span class="fu">unique</span>(airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(valores_unicos_cod_postal_limpios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "28004"  "28015"  "28013"  "28005"  "28012"  "28014"  "28045"  NA      
 [9] "28007"  "28028"  "28009"  "28001"  "28006"  "28010"  "28002"  "28034" 
[17] "28050"  "28008"  "28011"  "28049"  "28038"  "28053"  "28047"  "28025" 
[25] "28019"  "28024"  "28016"  "28036"  "28046"  "28039"  "28020"  "28003" 
[33] "28029"  "28054"  "28041"  "28026"  "28058"  "28018"  "28030"  "28017" 
[41] "28027"  "28043"  "28033"  "28055"  "28021"  "28032"  "28037"  "28022" 
[49] "28042"  "28094"  "280013" "28035"  "28040"  "28031"  "28044"  "28105" 
[57] "28023"  "28051"  "28850"  "28048"  "28056"  "28060"  "28052" </code></pre>
</div>
</div>
<p>Observo un error en el código postal 280013:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>airbnb <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CodigoPostal =</span> <span class="fu">ifelse</span>(CodigoPostal <span class="sc">==</span> <span class="st">"280013"</span>, <span class="st">"28013"</span>, CodigoPostal))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificamos el cambio</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">unique</span>(airbnb<span class="sc">$</span>CodigoPostal))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "28004" "28015" "28013" "28005" "28012" "28014" "28045" NA      "28007"
[10] "28028" "28009" "28001" "28006" "28010" "28002" "28034" "28050" "28008"
[19] "28011" "28049" "28038" "28053" "28047" "28025" "28019" "28024" "28016"
[28] "28036" "28046" "28039" "28020" "28003" "28029" "28054" "28041" "28026"
[37] "28058" "28018" "28030" "28017" "28027" "28043" "28033" "28055" "28021"
[46] "28032" "28037" "28022" "28042" "28094" "28035" "28040" "28031" "28044"
[55] "28105" "28023" "28051" "28850" "28048" "28056" "28060" "28052"</code></pre>
</div>
</div>
<hr>
<p><strong>4. ¿Cuáles son los 5 códigos postales con más entradas? ¿Y con menos? ¿Cuántas entradas tienen?</strong></p>
<p>Códigos con más entradas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>codigos_mas_entradas <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(CodigoPostal) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">NumEntradas =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(NumEntradas)) <span class="sc">%&gt;%</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(CodigoPostal)) <span class="sc">%&gt;%</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(codigos_mas_entradas)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  CodigoPostal NumEntradas
  &lt;chr&gt;              &lt;int&gt;
1 28012               2060
2 28004               1795
3 28005               1195
4 28013               1020
5 28014                630</code></pre>
</div>
</div>
<p>Códigos con menos entradas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>codigos_menos_entradas <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(CodigoPostal) <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">NumEntradas =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(NumEntradas) <span class="sc">%&gt;%</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(CodigoPostal)) <span class="sc">%&gt;%</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(codigos_menos_entradas)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  CodigoPostal NumEntradas
  &lt;chr&gt;              &lt;int&gt;
1 28048                  1
2 28052                  1
3 28056                  1
4 28058                  1
5 28060                  1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>codigos_menos_entradas_2 <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(CodigoPostal) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">NumEntradas =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">'drop'</span>) <span class="sc">%&gt;%</span> <span class="co"># Agrega .groups = 'drop' para evitar un warning en dplyr 1.0.0 o superior</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(NumEntradas) <span class="sc">%&gt;%</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(CodigoPostal)) <span class="sc">%&gt;%</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(NumEntradas <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(codigos_menos_entradas_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 2
  CodigoPostal NumEntradas
  &lt;chr&gt;              &lt;int&gt;
1 28048                  1
2 28052                  1
3 28056                  1
4 28058                  1
5 28060                  1
6 28094                  1
7 28105                  1
8 28850                  1</code></pre>
</div>
</div>
<p>Hay 8 códigos postales con el menor número de entradas (1).</p>
<hr>
<p><strong>5. ¿Cuáles son los barrios que hay en el código postal 28012?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>barrios_codpostal_28012 <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(CodigoPostal <span class="sc">==</span> <span class="st">'28012'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Barrio) <span class="sc">%&gt;%</span>    <span class="co"># Elige la columna Barrio</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>()            <span class="co"># Extrae valores únicos de la columna Barrio</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los resultados</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(barrios_codpostal_28012)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Barrio
1              Sol
2          Acacias
3  Palos de Moguer
4      Embajadores
5           Cortes
6          Palacio
7      Universidad
8         Delicias
9         Arapiles
10          Atocha
11            Goya</code></pre>
</div>
</div>
<hr>
<p><strong>6. ¿Cuántas entradas hay en cada uno de esos barrios para el código postal 28012?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>entradas_por_barrio_28012 <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(CodigoPostal <span class="sc">==</span> <span class="st">'28012'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Barrio) <span class="sc">%&gt;%</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">NumEntradas =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(NumEntradas))</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los datos</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(entradas_por_barrio_28012)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 2
   Barrio          NumEntradas
   &lt;fct&gt;                 &lt;int&gt;
 1 Embajadores            1449
 2 Sol                     301
 3 Cortes                  216
 4 Palos de Moguer          46
 5 Palacio                  27
 6 Acacias                  13
 7 Universidad               4
 8 Arapiles                  1
 9 Atocha                    1
10 Delicias                  1
11 Goya                      1</code></pre>
</div>
</div>
<hr>
<p><strong>7. ¿Cuántos barrios hay en todo el dataset airbnb? ¿Cuáles son?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>barrios_unicos <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Barrio) <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>() <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Barrio)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>num_barrios_unicos <span class="ot">&lt;-</span> <span class="fu">nrow</span>(barrios_unicos)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"En todo el dataset airbnb hay"</span>, num_barrios_unicos, <span class="st">"barrios."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "En todo el dataset airbnb hay 125 barrios."</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar todos los barrios</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(barrios_unicos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Barrio
1                       Abrantes
2                        Acacias
3                        Adelfas
4                     Aeropuerto
5                        Aguilas
6               Alameda de Osuna
7                        Almagro
8                       Almenara
9                    Almendrales
10                        Aluche
11                        Ambroz
12                       Amposta
13              Apostol Santiago
14                      Arapiles
15                       Aravaca
16                         Arcos
17                     Argüelles
18                        Atocha
19                 Bellas Vistas
20                    Berruguete
21                    Buenavista
22                      Butarque
23                    Campamento
24                      Canillas
25                    Canillejas
26                      Cármenes
27                 Casa de Campo
28    Casco Histórico de Barajas
29   Casco Histórico de Vallecas
30  Casco Histórico de Vicálvaro
31                    Castellana
32                      Castilla
33                   Castillejos
34                       Chopera
35                 Ciudad Jardín
36          Ciudad Universitaria
37                        Colina
38                      Comillas
39                    Concepción
40                    Corralejos
41                        Cortes
42                   Costillares
43                Cuatro Caminos
44                Cuatro Vientos
45                      Delicias
46                     El Goloso
47                    El Plantío
48                       El Viso
49                   Embajadores
50                     Entrevías
51                      Estrella
52                     Fontarrón
53              Fuente del Berro
54                 Fuentelareina
55                    Gaztambide
56                          Goya
57                    Guindalera
58                        Hellín
59                Hispanoamérica
60                         Ibiza
61                      Imperial
62                     Jerónimos
63                      Justicia
64                        La Paz
65                       Legazpi
66                         Lista
67                   Los Angeles
68                   Los Rosales
69                        Lucero
70                    Marroquina
71                   Media Legua
72                    Mirasierra
73                      Moscardó
74                    Niño Jesús
75                  Nueva España
76                      Numancia
77                        Opañel
78                     Orcasitas
79                       Orcasur
80                      Pacífico
81                       Palacio
82                       Palomas
83               Palomeras Bajas
84             Palomeras Sureste
85               Palos de Moguer
86                       Pavones
87                    Peñagrande
88                         Pilar
89                 Pinar del Rey
90                       Piovera
91                      Portazgo
92                    Pradolongo
93                   Prosperidad
94                  Pueblo Nuevo
95                 Puerta Bonita
96              Puerta del Angel
97                      Quintana
98                     Recoletos
99                         Rejas
100                   Rios Rosas
101                        Rosas
102                     Salvador
103                   San Andrés
104                San Cristobal
105                    San Diego
106                   San Fermín
107                   San Isidro
108            San Juan Bautista
109                  San Pascual
110                Santa Eugenia
111                     Simancas
112                          Sol
113                        Timón
114                    Trafalgar
115                  Universidad
116                Valdeacederas
117                 Valdefuentes
118                   Valdemarín
119                   Valdezarza
120                 Vallehermoso
121                     Valverde
122                       Ventas
123                    Vinateros
124                 Vista Alegre
125                        Zofío</code></pre>
</div>
</div>
<hr>
<p><strong>8. ¿Cuáles son los 5 barrios que tienen mayor número entradas?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>top_5_barrios <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Barrio) <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">NumEntradas =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(NumEntradas)) <span class="sc">%&gt;%</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(top_5_barrios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  Barrio      NumEntradas
  &lt;fct&gt;             &lt;int&gt;
1 Embajadores        1844
2 Universidad        1358
3 Palacio            1083
4 Sol                 940
5 Justicia            785</code></pre>
</div>
</div>
<hr>
<p><strong>9. ¿Cuántos Tipos de Alquiler diferentes hay? ¿Cuáles son? ¿Cuántas entradas en el dataframe hay por cada tipo?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tipos diferentes de alquiler</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>tipos_alquiler <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(TipoAlquiler) <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>()</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Cuántos Tipos de Alquiler diferentes hay</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>num_tipos_alquiler <span class="ot">&lt;-</span> <span class="fu">nrow</span>(tipos_alquiler)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Hay"</span>, num_tipos_alquiler, <span class="st">"Tipos de Alquiler diferentes"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Hay 3 Tipos de Alquiler diferentes"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tipos_alquiler)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     TipoAlquiler
1    Private room
2 Entire home/apt
3     Shared room</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Entradas por cada Tipo de Alquiler</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>entradas_por_tipo_alquiler <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TipoAlquiler) <span class="sc">%&gt;%</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">NumEntradas =</span> <span class="fu">n</span>())</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(entradas_por_tipo_alquiler)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  TipoAlquiler    NumEntradas
  &lt;fct&gt;                 &lt;int&gt;
1 Entire home/apt        7903
2 Private room           5113
3 Shared room             191</code></pre>
</div>
</div>
<p><strong>Muestra el diagrama de cajas del precio para cada uno de los diferentes Tipos de Alquiler</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(airbnb, <span class="fu">aes</span>(<span class="at">x =</span> Precio, <span class="at">y =</span> TipoAlquiler, <span class="at">fill =</span> TipoAlquiler)) <span class="sc">+</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Diagrama de Cajas de Precio por Tipo de Alquiler"</span>,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Precio"</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Tipos de Alquiler"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 9 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="AirbnbAnalysis_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><strong>10. Cuál es el precio medio de alquiler de cada uno, la diferencia que hay ¿es estadísticamente significativa? ¿Con qué test lo comprobarías?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>precios_alquiler <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TipoAlquiler) <span class="sc">%&gt;%</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">PrecioMedio =</span> <span class="fu">mean</span>(Precio, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Además de conocer el precio medio queremos saber:</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">PrecioMaximo =</span> <span class="fu">max</span>(Precio, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">PrecioMinimo =</span> <span class="fu">min</span>(Precio, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(precios_alquiler)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  TipoAlquiler    PrecioMedio PrecioMaximo PrecioMinimo
  &lt;fct&gt;                 &lt;dbl&gt;        &lt;int&gt;        &lt;int&gt;
1 Entire home/apt        87.3          875           10
2 Private room           34.3          650            9
3 Shared room            29.9          328           10</code></pre>
</div>
</div>
<p>Para determinar si las diferencias en los precios medios son estadísticamente significativas, podemos realizar un análisis de varianza (ANOVA) si se cumplen ciertas suposiciones, o un test no paramétrico como el test de Kruskal-Wallis si esas suposiciones no se cumplen.</p>
<p>Suposiciones para ANOVA: - Normalidad: Los residuos de cada grupo deben distribuirse normalmente. - Homogeneidad de varianzas: Las varianzas entre los grupos deben ser similares. - Independencia: Las observaciones deben ser independientes entre sí.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>varianza_precios <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TipoAlquiler) <span class="sc">%&gt;%</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Varianza =</span> <span class="fu">var</span>(Precio, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(varianza_precios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  TipoAlquiler    Varianza
  &lt;fct&gt;              &lt;dbl&gt;
1 Entire home/apt    3415.
2 Private room       1006.
3 Shared room        1652.</code></pre>
</div>
</div>
<p>La diferencia en las varianzas puede reflejar la diversidad en los tipos de propiedades y los rangos de precios dentro de cada categoría. Por ejemplo, las casas o apartamentos enteros pueden variar significativamente en tamaño, ubicación y lujo, lo que podría explicar una varianza más alta en sus precios.</p>
<p><strong>Si estas suposiciones no se cumplen (homogeneidad), los resultados del ANOVA pueden no ser fiables:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>resultado_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Precio <span class="sc">~</span> TipoAlquiler, <span class="at">data =</span> airbnb)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(resultado_anova)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Df   Sum Sq Mean Sq F value Pr(&gt;F)    
TipoAlquiler     2  8981217 4490608    1828 &lt;2e-16 ***
Residuals    13195 32417217    2457                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
9 observations deleted due to missingness</code></pre>
</div>
</div>
<p>Los resultados del análisis ANOVA sugieren que <strong>hay diferencias estadísticamente significativas en los precios medios</strong> entre los diferentes tipos de alquiler.</p>
<ul>
<li><code>Residuals: 13195</code>: Representa la variabilidad dentro de los grupos.</li>
<li><code>FPr(&gt;F): &lt;2e-16</code> (esencialmente 0). Este es el p-valor. Un p-valor muy bajo (aquí prácticamente 0) indica que la diferencia en los precios medios entre los diferentes tipos de alquiler no es probable que se deba al azar.</li>
<li>Los asteriscos <code>"***"</code> indican un <strong>nivel de significancia muy alto.</strong> En estadística convencional, esto sería mucho menor que 0.001, lo que significa que hay menos de una probabilidad de 0.1% de que estas diferencias sean aleatorias.</li>
<li>Se indica que <code>9</code> observaciones fueron eliminadas debido a datos faltantes. Esto es importante tener en cuenta ya que los datos faltantes pueden influir en los resultados.</li>
</ul>
<p><strong>Como las suposiciones anteriores no se cumplen, usamos el test de Kruskal-Wallis:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>resultado_kruskal <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(Precio <span class="sc">~</span>TipoAlquiler, <span class="at">data =</span> airbnb)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(resultado_kruskal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  Precio by TipoAlquiler
Kruskal-Wallis chi-squared = 7235.6, df = 2, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>La prueba de Kruskal-Wallis es una alternativa no paramétrica al ANOVA, utilizada cuando los datos no cumplen con las suposiciones de normalidad o homogeneidad de varianzas.</p>
<p>La prueba confirma que hay diferencias significativas en los precios entre los distintos tipos de alquiler. Sin embargo, esta prueba no especifica entre qué grupos particulares existen estas diferencias.</p>
<hr>
<p><strong>11. Filtra el dataframe cuyos tipo de alquiler sea ‘Entire home/apt’ y guárdalo en un dataframe llamado <em>airbnb_entire</em>. Estas serán las entradas que tienen un alquiler del piso completo.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrando el dataframe</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>airbnb_entire <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(TipoAlquiler <span class="sc">==</span> <span class="st">"Entire home/apt"</span>)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar las primeras filas para verificar</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb_entire)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  CodigoPostal      Barrio TipoPropiedad    TipoAlquiler MaxOcupantes NumBanyos
1        28004 Universidad     Apartment Entire home/apt            6         1
2        28004 Universidad     Apartment Entire home/apt            3         1
3        28004 Universidad          Loft Entire home/apt            3         2
4        28015 Universidad     Apartment Entire home/apt            5         1
5        28004 Universidad     Apartment Entire home/apt            2         1
6        28004 Universidad     Apartment Entire home/apt            3         1
  NumDormitorios NumCamas TipoCama
1              3        5 Real Bed
2              2        2 Real Bed
3              1        1 Real Bed
4              1        1 Real Bed
5              0        1 Real Bed
6              1       NA Real Bed
                                                                                                                                                                                                                                                                                                                                                       Comodidades
1                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
2                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
3                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
4                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
5 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
6                                                                                                                                                                                                                                                       TV,Wireless Internet,Air conditioning,Kitchen,Elevator in building,Buzzer/wireless intercom,Heating,Washer
  PiesCuadrados Precio Puntuacion MetrosCuadrados
1            NA     92         96              NA
2            NA     55         91              NA
3            NA     60        100              NA
4           538     75         90        49.98181
5            NA     55         95              NA
6            NA     70         84              NA</code></pre>
</div>
</div>
<hr>
<ol start="12" type="1">
<li><strong>¿Cuáles son los 5 barrios que tienen un mayor número de apartamentos enteros en alquiler?</strong> Nota: Mirar solo en airbnb_entire. A partir de este punto y hasta que se diga lo contrario partiremos de airbnb_entire.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>top_5_barrios_entire <span class="ot">&lt;-</span> airbnb_entire <span class="sc">%&gt;%</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Barrio) <span class="sc">%&gt;%</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">NumApartamentos =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(NumApartamentos)) <span class="sc">%&gt;%</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(top_5_barrios_entire)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  Barrio      NumApartamentos
  &lt;fct&gt;                 &lt;int&gt;
1 Embajadores            1228
2 Universidad             984
3 Palacio                 769
4 Sol                     701
5 Cortes                  574</code></pre>
</div>
</div>
<hr>
<p><strong>13. ¿Cuáles son los 5 barrios que tienen un mayor precio medio de alquiler para apartamentos enteros (es decir, del dataframe airbnb_entire)?¿Cuál es su precio medio?</strong></p>
<p>Ayuda: Usa la función aggregate <code>aggregate(.~colname,df,mean,na.rm=TRUE)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>top_5_barrios_precio_medio <span class="ot">&lt;-</span> airbnb_entire <span class="sc">%&gt;%</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Barrio) <span class="sc">%&gt;%</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">PrecioMedio =</span> <span class="fu">mean</span>(Precio, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(PrecioMedio)) <span class="sc">%&gt;%</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(top_5_barrios_precio_medio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  Barrio        PrecioMedio
  &lt;fct&gt;               &lt;dbl&gt;
1 Palomas              310.
2 Fuentelareina        180 
3 Recoletos            162.
4 El Plantío           150 
5 Castellana           141.</code></pre>
</div>
</div>
<p>Usando <code>aggregate()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculando el precio medio por barrio</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>precio_medio_por_barrio <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(Precio <span class="sc">~</span> Barrio, airbnb_entire, mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordenando y seleccionando los 5 barrios con el mayor precio medio</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>top_5_barrios_precio_medio_2 <span class="ot">&lt;-</span> <span class="fu">head</span>(precio_medio_por_barrio[<span class="fu">order</span>(<span class="sc">-</span>precio_medio_por_barrio<span class="sc">$</span>Precio), ], <span class="dv">5</span>)</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(top_5_barrios_precio_medio_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Barrio   Precio
77       Palomas 309.7500
50 Fuentelareina 180.0000
93     Recoletos 161.9254
43    El Plantío 150.0000
30    Castellana 141.3889</code></pre>
</div>
</div>
<p>La función <code>aggregate()</code> se utiliza para aplicar una función a un conjunto de valores agrupados. En este caso, aplicamos la función <code>mean</code> para calcular el precio medio, agrupando por Barrio. El <code>na.rm = TRUE</code> indica que se debemos ignorar los valores NA en el cálculo del promedio.</p>
<p><code>Precio ~ Barrio</code>: Esta es la fórmula utilizada por <code>aggregate()</code>. El lado izquierdo de <code>~</code> (Precio) es la variable sobre la cual se aplica la función (en este caso, calcular el promedio), y el lado derecho (Barrio) es la variable por la cual se agrupan los datos. En otras palabras, esta fórmula indica que queremos agrupar el dataframe por la columna Barrio y luego calcular una medida (el promedio) para la columna Precio dentro de cada grupo de Barrio.</p>
<hr>
<p><strong>14. ¿Cuántos apartamentos hay en cada uno de esos barrios?</strong></p>
<p>Mostrar una dataframe con el nombre del barrio, el precio y el número de entradas.</p>
<p>Ayuda: Podéis crear un nuevo dataframe con las columnas “Barrio” y “Freq” que contenga el número de entradas en cada barrio y hacer un merge con el dataframe del punto anterior.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Contar el número de apartamentos en cada barrio</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>num_apartamentos_por_barrio <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(<span class="fu">cbind</span>(<span class="at">NumApartamentos =</span> Barrio) <span class="sc">~</span> Barrio, <span class="at">data =</span> airbnb_entire, <span class="at">FUN =</span> length)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Hacer un merge de los dataframes</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>resultado_final <span class="ot">&lt;-</span> <span class="fu">merge</span>(top_5_barrios_precio_medio_2, num_apartamentos_por_barrio, <span class="at">by =</span> <span class="st">"Barrio"</span>)</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(resultado_final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Barrio   Precio NumApartamentos
1    Castellana 141.3889              73
2    El Plantío 150.0000               1
3 Fuentelareina 180.0000               2
4       Palomas 309.7500               4
5     Recoletos 161.9254             135</code></pre>
</div>
</div>
<p><code>cbind(NumApartamentos = Barrio) ~ Barrio</code> crea una columna llamada <code>NumApartamentos</code> y la utiliza para contar las entradas en cada barrio.</p>
<hr>
<p><strong>15. Partiendo del dataframe anterior, muestra los 5 barrios con mayor precio, pero que tengan más de 100 entradas de alquiler.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Contar entradas y calcular el precio medio por barrio</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>data_barrios <span class="ot">&lt;-</span> airbnb_entire <span class="sc">%&gt;%</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Barrio) <span class="sc">%&gt;%</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">NumEntradas =</span> <span class="fu">n</span>(),</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">PrecioMedio =</span> <span class="fu">mean</span>(Precio, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar los Barrios con Más de 100 Entradas</span></span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>barrios_filtrados <span class="ot">&lt;-</span> data_barrios <span class="sc">%&gt;%</span></span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(NumEntradas <span class="sc">&gt;</span> <span class="dv">100</span>)</span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordenar por precio medio y seleccionar los 5 primeros</span></span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a>top_5_barrios <span class="ot">&lt;-</span> barrios_filtrados <span class="sc">%&gt;%</span></span>
<span id="cb69-13"><a href="#cb69-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(PrecioMedio)) <span class="sc">%&gt;%</span></span>
<span id="cb69-14"><a href="#cb69-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb69-15"><a href="#cb69-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-16"><a href="#cb69-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(top_5_barrios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  Barrio    NumEntradas PrecioMedio
  &lt;fct&gt;           &lt;int&gt;       &lt;dbl&gt;
1 Recoletos         135       162. 
2 Goya              142       111. 
3 Sol               701       101. 
4 Trafalgar         223        98.6
5 Justicia          534        98.3</code></pre>
</div>
</div>
<hr>
<p><strong>16. Dibuja el diagrama de densidad de distribución de los diferentes precios. Serían 5 gráficas, una por cada barrio.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar el dataset para incluir solo los 5 barrios principales</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>datos_filtrados <span class="ot">&lt;-</span> airbnb_entire <span class="sc">%&gt;%</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Barrio <span class="sc">%in%</span> top_5_barrios<span class="sc">$</span>Barrio)</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el diagrama de densidad</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos_filtrados, <span class="fu">aes</span>(<span class="at">x =</span> Precio, <span class="at">fill =</span> Barrio)) <span class="sc">+</span></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Barrio) <span class="sc">+</span></span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Densidad de Distribución de Precios por Barrio"</span>,</span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Precio"</span>,</span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="AirbnbAnalysis_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><strong>17. Calcula el tamaño medio, en metros cuadrados, para los 5 barrios anteriores y muestralo en el mismo dataframe junto con el precio y número de entradas.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el tamaño medio en metros cuadrados para los 5 barrios principales</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>tamaño_medio_por_barrio <span class="ot">&lt;-</span> datos_filtrados <span class="sc">%&gt;%</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Barrio) <span class="sc">%&gt;%</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(TamañoMedio <span class="ot">=</span> <span class="fu">mean</span>(MetrosCuadrados, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Combinando con los datos de precio medio y número de entradas</span></span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>datos_finales <span class="ot">&lt;-</span> <span class="fu">merge</span>(top_5_barrios, tamaño_medio_por_barrio, <span class="at">by =</span> <span class="st">"Barrio"</span>)</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los resultados</span></span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(datos_finales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Barrio NumEntradas PrecioMedio TamañoMedio
1      Goya         142   111.33803    51.68504
2  Justicia         534    98.25468    28.52669
3 Recoletos         135   161.92537    26.66316
4       Sol         701   100.75036    45.61692
5 Trafalgar         223    98.57848    29.30426</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordenando el dataframe final por tamaño medio</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>datos_finales_ordenados <span class="ot">&lt;-</span> datos_finales <span class="sc">%&gt;%</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(TamañoMedio))</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrando los resultados</span></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(datos_finales_ordenados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Barrio NumEntradas PrecioMedio TamañoMedio
1      Goya         142   111.33803    51.68504
2       Sol         701   100.75036    45.61692
3 Trafalgar         223    98.57848    29.30426
4  Justicia         534    98.25468    28.52669
5 Recoletos         135   161.92537    26.66316</code></pre>
</div>
</div>
<hr>
<p><strong>18. Dibuja el diagrama de densidad de distribución de los diferentes tamaños de apartamentos. Serían 5 gráficas, una por cada barrio.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos_filtrados, <span class="fu">aes</span>(<span class="at">x =</span> MetrosCuadrados, <span class="at">fill =</span> Barrio)) <span class="sc">+</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Barrio) <span class="sc">+</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Densidad de Distribución de Tamaños de Apartamentos por Barrio"</span>,</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Tamaño en Metros Cuadrados"</span>,</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1645 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="AirbnbAnalysis_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><strong>19. Esta claro que las medias de metros cuadrados de cada uno de estos 5 barrios parecen ser diferentes, pero ¿son estadísticamente diferentes? ¿Que test habría que usar para comprobarlo?</strong></p>
<p>El tipo de test a utilizar dependerá de si los datos cumplen ciertas suposiciones estadísticas, principalmente la normalidad y la homogeneidad de las varianzas.</p>
<p><strong>Opciones de Test:</strong></p>
<ol type="1">
<li><strong>ANOVA (Análisis de Varianza)</strong>: Si los datos cumplen con la suposición de normalidad (los tamaños de los apartamentos en cada barrio se distribuyen normalmente) y homogeneidad de varianzas (las varianzas son similares entre los grupos), entonces ANOVA es una opción adecuada.</li>
</ol>
<p>Para verificar la <em>normalidad</em>, podemos usar pruebas como Shapiro-Wilk (para muestras pequeñas) o Kolmogorov-Smirnov (para muestras más grandes), además de gráficos Q-Q.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificación de Normalidad: Prueba de Shapiro-Wilk</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(datos_filtrados<span class="sc">$</span>MetrosCuadrados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  datos_filtrados$MetrosCuadrados
W = 0.82315, p-value = 5.323e-09</code></pre>
</div>
</div>
<p>El resultado de la prueba de Shapiro-Wilk sugiere que la distribución de la variable <code>MetrosCuadrados</code> del dataset <code>datos_filtrados</code> no sigue una distribución normal.</p>
<p><strong>Interpretación:</strong></p>
<ul>
<li><p><strong>W (Estadístico de Shapiro-Wilk)</strong>: El valor de <code>W = 0.82315</code> es el estadístico de la prueba. Los valores de W cercanos a 1 sugieren una distribución más normal. Un valor de 0.82315 indica una cierta desviación de la normalidad, pero la interpretación más precisa viene del valor p.</p></li>
<li><p><strong>Valor p</strong>: El valor p es muy pequeño (<code>p-value = 5.323e-09</code>, lo cual es esencialmente cero para la mayoría de los propósitos prácticos). En las pruebas de hipótesis, un valor p pequeño (generalmente menor que 0.05) indica que hay evidencia suficiente para rechazar la hipótesis nula. En el contexto de la prueba de Shapiro-Wilk, la hipótesis nula es que los datos están normalmente distribuidos. Por lo tanto, un valor p tan pequeño sugiere que debemos rechazar la hipótesis nula de normalidad.</p></li>
</ul>
<p><strong>Implicaciones para el Análisis:</strong></p>
<ul>
<li><p><strong>Análisis Subsiguiente</strong>: Si teníamos la intención de utilizar métodos estadísticos que asumen normalidad (como ciertos tipos de ANOVA o regresiones lineales), este resultado indica que debemos tener precaución. Puede ser adecuado considerar métodos alternativos que no asuman normalidad, o transformar los datos para aproximarse más a una distribución normal.</p></li>
<li><p><strong>Transformaciones de Datos</strong>: En algunos casos, transformar los datos (por ejemplo, usando logaritmos o raíces cuadradas) puede hacer que se ajusten mejor a una distribución normal.</p></li>
<li><p><strong>Métodos No Paramétricos</strong>: Si estamos realizando comparaciones entre grupos, los métodos no paramétricos (como la prueba de Mann-Whitney o el test de Kruskal-Wallis) pueden ser más adecuados, ya que no asumen una distribución normal de los datos.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificación de Normalidad: Gráficos Q-Q (Quantile-Quantile)</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(datos_filtrados<span class="sc">$</span>MetrosCuadrados)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(datos_filtrados<span class="sc">$</span>MetrosCuadrados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AirbnbAnalysis_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="2" type="1">
<li><strong>Kruskal-Wallis Test</strong>: Si los datos no cumplen con estas suposiciones, el test de Kruskal-Wallis, que es un test no paramétrico, sería más adecuado. Este test no requiere la suposición de normalidad y es útil cuando se comparan medianas en lugar de medias entre grupos.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>resultado_kruskal <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(MetrosCuadrados <span class="sc">~</span> Barrio, <span class="at">data =</span> datos_filtrados)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(resultado_kruskal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  MetrosCuadrados by Barrio
Kruskal-Wallis chi-squared = 1.882, df = 4, p-value = 0.7574</code></pre>
</div>
</div>
<p>El resultado de la prueba de Kruskal-Wallis indica que no hay diferencias estadísticamente significativas en las medianas de la variable <code>MetrosCuadrados</code> entre los diferentes barrios. Esto se deduce de:</p>
<ul>
<li><p>El valor de <code>Kruskal-Wallis chi-squared = 1.882</code> es el estadístico de la prueba, que en este caso no es tan relevante como el valor p para la interpretación.</p></li>
<li><p>Grados de Libertad (df): Los <code>df = 4</code> indican que se compararon 5 grupos (barrios) en total, ya que los grados de libertad para la prueba de Kruskal-Wallis son <code>número de grupos - 1</code>.</p></li>
<li><p>Valor p: El <code>p-value = 0.7574</code> es mucho mayor que el umbral comúnmente utilizado de 0.05 para determinar la significancia estadística. Un <strong>p valor alto</strong> como este sugiere que no hay evidencia suficiente para rechazar la hipótesis nula de la prueba de Kruskal-Wallis, que afirma que todas las medianas de grupo son iguales.</p></li>
</ul>
<hr>
<p>Para únicamente los pisos de alquiler en el barrio de Sol:</p>
<p><code>barrio_sol&lt;-subset(airbnb_entire,Barrio=="Sol")</code></p>
<p>Calcular un modelo lineal que combine alguna de estas variables: * NumBanyos * NumDormitorios * MaxOcupantes * MetrosCuadrados</p>
<ol start="20" type="1">
<li>Primero <strong>calculamos la correlación para ver como se relacionan estas variables entre sí.</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>barrio_sol <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire,Barrio <span class="sc">==</span> <span class="st">"Sol"</span>)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(barrio_sol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   CodigoPostal Barrio TipoPropiedad    TipoAlquiler MaxOcupantes NumBanyos
10        28013    Sol     Apartment Entire home/apt            4         1
11        28013    Sol   Condominium Entire home/apt            6         1
12        28013    Sol     Apartment Entire home/apt            4         1
13        28012    Sol     Apartment Entire home/apt            6         1
14        28013    Sol     Apartment Entire home/apt            4         1
15        28013    Sol     Apartment Entire home/apt            4         1
   NumDormitorios NumCamas TipoCama
10              1        1 Real Bed
11              2        3 Real Bed
12              1        2 Real Bed
13              2        2 Real Bed
14              1        2 Real Bed
15              1        2 Real Bed
                                                                                                                                                                                                                                                                                                                 Comodidades
10                                                                                                                             TV,Wireless Internet,Air conditioning,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Family/kid friendly,Suitable for events,Washer,Essentials,Hangers,Hair dryer,Iron
11                                                                                                                                   TV,Wireless Internet,Air conditioning,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Family/kid friendly,Washer,Dryer,Essentials,Shampoo,Hangers,Hair dryer,Iron
12 TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Family/kid friendly,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace
13                                                                                        TV,Internet,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Elevator in building,Buzzer/wireless intercom,Heating,Family/kid friendly,Washer,Dryer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
14                                                                                                                                                                            TV,Internet,Wireless Internet,Air conditioning,Kitchen,Heating,Washer,Essentials,Hangers,Hair dryer,translation missing: en.hosting_amenity_50
15                                                                                                                                                         TV,Wireless Internet,Kitchen,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Laptop friendly workspace
   PiesCuadrados Precio Puntuacion MetrosCuadrados
10           646     75         91        60.01534
11            NA    130        100              NA
12            NA    100         97              NA
13            NA    160         95              NA
14            NA     49         95              NA
15            NA     70         88              NA</code></pre>
</div>
</div>
<p><code>subset(airbnb_entire, Barrio == "Sol")</code> selecciona las filas del dataframe <code>airbnb_entire</code> donde el <code>Barrio</code> es “Sol”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la matriz de correlación</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>correlaciones <span class="ot">&lt;-</span> <span class="fu">cor</span>(barrio_sol[,<span class="fu">c</span>(<span class="st">"NumBanyos"</span>, <span class="st">"NumDormitorios"</span>, <span class="st">"MaxOcupantes"</span>, <span class="st">"MetrosCuadrados"</span>)], <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(correlaciones)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                NumBanyos NumDormitorios MaxOcupantes MetrosCuadrados
NumBanyos       1.0000000      0.6873719    0.7017290       0.4820549
NumDormitorios  0.6873719      1.0000000    0.7853809       0.5684521
MaxOcupantes    0.7017290      0.7853809    1.0000000       0.4286233
MetrosCuadrados 0.4820549      0.5684521    0.4286233       1.0000000</code></pre>
</div>
</div>
<p><code>cor(..., use = "complete.obs")</code> calcula la matriz de correlación para las columnas especificadas, excluyendo las observaciones con valores faltantes (<code>NA</code>).</p>
<p>Esta matriz de correlación muestra cómo cada par de variables está relacionado, con valores de correlación que varían entre -1 (correlación negativa perfecta) y 1 (correlación positiva perfecta). Un valor cercano a 1 indica una correlación positiva fuerte, cerca de -1 indica una correlación negativa fuerte y cerca de 0 indica poca o ninguna correlación lineal.</p>
<p><strong>Interpretación de tus Resultados:</strong></p>
<ul>
<li><code>NumBanyos y NumDormitorios</code>: Con una correlación de aproximadamente 0.687, hay una correlación positiva moderada a fuerte, sugiriendo que los apartamentos con más baños tienden a tener más dormitorios.</li>
<li><code>NumBanyos y MaxOcupantes</code>: Con una correlación de aproximadamente 0.702, también muestra una correlación positiva moderada a fuerte, lo que indica que los apartamentos con más baños tienden a acomodar a más personas.</li>
<li><code>NumDormitorios y MaxOcupantes</code>: Con una correlación de 0.785, esta es una de las correlaciones más fuertes en el dataset, lo que indica que los apartamentos con más dormitorios suelen tener capacidad para más ocupantes.</li>
<li><code>MetrosCuadrados</code> con otras variables: Las correlaciones varían entre 0.428 y 0.568, lo que sugiere que, aunque hay alguna relación positiva entre el tamaño del apartamento y las otras variables, esta relación no es tan fuerte como las relaciones entre las variables de número de baños, dormitorios y ocupantes.</li>
</ul>
<hr>
<ol start="21" type="1">
<li>Se observa que la correlación entre el número de dormitorios y los metros cuadrados es sorprendentemente baja. <strong>¿Son de fiar esos números?</strong></li>
</ol>
<p>Mediante un histograma o curvas de densidad podemos descartar números que no tienen sentido en el dataframe <code>barrio_sol</code>, para tener una matriz de correlación que tenga mayor sentido.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrio_sol, <span class="fu">aes</span>(<span class="at">x =</span> NumDormitorios)) <span class="sc">+</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>, <span class="at">color=</span><span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histograma de Número de Dormitorios"</span>,</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Número de Dormitorios"</span>,</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AirbnbAnalysis_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrio_sol, <span class="fu">aes</span>(<span class="at">x =</span> MetrosCuadrados)) <span class="sc">+</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">10</span>, <span class="at">fill =</span> <span class="st">"red"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>, <span class="at">color=</span><span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histograma de Metros Cuadratos"</span>,</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Metros Cuadrados"</span>,</span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 641 rows containing non-finite values (`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="AirbnbAnalysis_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Curvas de Densidad:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Curva de Densidad para NumDormitorios</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrio_sol, <span class="fu">aes</span>(<span class="at">x =</span> NumDormitorios)) <span class="sc">+</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Curva de Densidad de Número de Dormitorios"</span>, <span class="at">x =</span> <span class="st">"Número de Dormitorios"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AirbnbAnalysis_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Curva de Densidad para MetrosCuadrados</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrio_sol, <span class="fu">aes</span>(<span class="at">x =</span> MetrosCuadrados)) <span class="sc">+</span></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"red"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Curva de Densidad de Metros Cuadrados"</span>, <span class="at">x =</span> <span class="st">"Metros Cuadrados"</span>, <span class="at">y =</span> <span class="st">"Densidad"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 641 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="AirbnbAnalysis_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<ol start="22" type="1">
<li>Una vez que hayamos filtrado los datos correspondientes calcular el valor o la combinación de valores que mejor nos permite obtener el precio de un inmueble.</li>
</ol>
<p><strong>¿Qué variable es más fiable para conocer el precio de un inmueble, el número de habitaciones o los metros cuadrados?</strong></p>
<p><strong>Correlación:</strong> Calculamos el coeficiente de correlación (como Pearson) para cada variable con respecto al precio. Este coeficiente da una idea de cuán fuertemente está cada variable relacionada con el precio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlación con Precio</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(barrio_sol<span class="sc">$</span>Precio, barrio_sol<span class="sc">$</span>NumDormitorios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6542553</code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(barrio_sol<span class="sc">$</span>Precio, barrio_sol<span class="sc">$</span>MetrosCuadrados, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6381754</code></pre>
</div>
</div>
<p>Se decide añadir <code>use = "complete.obs"</code> para omitir los casos con valores NA.</p>
<ul>
<li><p><strong>Número de Dormitorios y Precio (0.6542553):</strong> Este coeficiente indica una correlación <em>positiva moderada</em> entre el número de dormitorios y el precio. A medida que aumenta el número de dormitorios, también tiende a aumentar el precio del inmueble.</p></li>
<li><p><strong>Metros Cuadrados y Precio (0.6381754):</strong> Este coeficiente, también <em>positivo</em> y cercano al anterior, sugiere una correlación <em>moderada</em> entre los metros cuadrados y el precio. Similarmente, a medida que aumenta el tamaño del inmueble en metros cuadrados, también tiende a aumentar su precio.</p></li>
</ul>
<p>Ambos coeficientes son relativamente cercanos, indicando que tanto el número de dormitorios como los metros cuadrados están moderadamente correlacionados con el precio de un inmueble. Sin embargo, el número de dormitorios tiene una correlación ligeramente más alta con el precio que los metros cuadrados en este conjunto de datos específico.</p>
<hr>
<ol start="23" type="1">
<li>Responde con su correspondiente margen de error del 95%, <strong>¿cuántos euros incrementa el precio del alquiler por cada metro cuadrado extra del piso?</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrio_sol, <span class="fu">aes</span>(<span class="at">x =</span> MetrosCuadrados, <span class="at">y =</span> Precio)) <span class="sc">+</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span> <span class="co"># Añade una línea de regresión</span></span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Diagrama de Dispersión de Alquileres"</span>,</span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Precio"</span>,</span>
<span id="cb98-8"><a href="#cb98-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Metros Cuadrado"</span></span>
<span id="cb98-9"><a href="#cb98-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 641 rows containing non-finite values (`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 641 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="AirbnbAnalysis_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regresión lineal simple</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(barrio_sol<span class="sc">$</span>Precio <span class="sc">~</span> barrio_sol<span class="sc">$</span>MetrosCuadrados, <span class="at">data =</span> barrio_sol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = barrio_sol$Precio ~ barrio_sol$MetrosCuadrados, 
    data = barrio_sol)

Coefficients:
               (Intercept)  barrio_sol$MetrosCuadrados  
                   69.5728                      0.6137  </code></pre>
</div>
</div>
<p>Por cada <strong>metro cuadrado adicional</strong>, el precio del inmueble aumenta en promedio <code>0.6137</code> unidades. El intercepto (<code>69.5728</code>) representa el precio estimado para un inmueble de cero metros cuadrados.</p>
<hr>
<ol start="24" type="1">
<li>Responde con su correspondiente margen de error del 95%, <strong>¿cuántos euros incrementa el precio del alquiler por cada habitación?</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regresión lineal simple</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(barrio_sol<span class="sc">$</span>Precio <span class="sc">~</span> barrio_sol<span class="sc">$</span>NumDormitorios, <span class="at">data =</span> barrio_sol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = barrio_sol$Precio ~ barrio_sol$NumDormitorios, data = barrio_sol)

Coefficients:
              (Intercept)  barrio_sol$NumDormitorios  
                    52.58                      33.36  </code></pre>
</div>
</div>
<p>Cada <strong>dormitorio adicional</strong> está asociado con un aumento promedio de <code>33.36</code> unidades en el precio del inmueble.</p>
<p>El intercepto (<code>52.58</code>) representa el precio estimado para un inmueble de cero dormitorios.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regresión múltiple</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(barrio_sol<span class="sc">$</span>Precio <span class="sc">~</span> barrio_sol<span class="sc">$</span>NumDormitorios <span class="sc">+</span> barrio_sol<span class="sc">$</span>MetrosCuadrados, <span class="at">data =</span> barrio_sol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = barrio_sol$Precio ~ barrio_sol$NumDormitorios + 
    barrio_sol$MetrosCuadrados, data = barrio_sol)

Coefficients:
               (Intercept)   barrio_sol$NumDormitorios  
                   48.2999                     22.3616  
barrio_sol$MetrosCuadrados  
                    0.3284  </code></pre>
</div>
</div>
<p>En este modelo, cada dormitorio adicional está asociado con un aumento promedio de <code>22.3616</code> unidades en el precio, manteniendo los metros cuadrados constantes. Por cada metro cuadrado adicional, el precio aumenta en promedio <code>0.3284</code> unidades, manteniendo el número de dormitorios constante.</p>
<p>El intercepto (<code>48.2999</code>) representa el precio estimado para un inmueble de cero dormitorios y cero metros cuadrados.</p>
<p>Estos modelos de regresión sugieren que tanto el número de dormitorios como los metros cuadrados son predictores significativos del precio de un inmueble, con el número de dormitorios teniendo una influencia más directa en el modelo de regresión simple, pero esta influencia se modifica cuando se consideran ambas variables juntas en un modelo de regresión múltiple.</p>
<hr>
<p><strong>25. ¿Cuál es la probabilidad de encontrar, en el barrio de Sol, un apartamento en alquiler con 3 dormitorios? ¿Cuál es el intervalo de confianza de esa probabilidad?</strong></p>
<p><strong>Método manual:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Nº de apartamentos en el barrio de Sol</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>num_apartamentos_sol <span class="ot">=</span> <span class="fu">nrow</span>(barrio_sol)</span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"El barrio de Sol tiene"</span>, num_apartamentos_sol, <span class="st">"apartamentos"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "El barrio de Sol tiene 701 apartamentos"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cuántos tienen 3 dormitorios</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>num_apartamentos_3_dormitorios <span class="ot">&lt;-</span> <span class="fu">sum</span>(barrio_sol<span class="sc">$</span>NumDormitorios <span class="sc">==</span> <span class="dv">3</span>)</span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(num_apartamentos_3_dormitorios, <span class="st">"apartamentos tienen 3 dormitorios"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "55 apartamentos tienen 3 dormitorios"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cálculo de la probabilidad</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>P <span class="ot">&lt;-</span> num_apartamentos_3_dormitorios <span class="sc">/</span> num_apartamentos_sol</span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Probabilidad:"</span>, P))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Probabilidad: 0.0784593437945792"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cálculo del intervalo de confianza</span></span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fl">1.96</span>  <span class="co"># Valor z para el 95% de confianza</span></span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>error_margen <span class="ot">&lt;-</span> z <span class="sc">*</span> <span class="fu">sqrt</span>((P <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> P)) <span class="sc">/</span> num_apartamentos_sol)</span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>intervalo_confianza <span class="ot">&lt;-</span> <span class="fu">c</span>(P <span class="sc">-</span> error_margen, P <span class="sc">+</span> error_margen)</span>
<span id="cb114-5"><a href="#cb114-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-6"><a href="#cb114-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir resultados</span></span>
<span id="cb114-7"><a href="#cb114-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Probabilidad:"</span>, P))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Probabilidad: 0.0784593437945792"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Intervalo de confianza: ["</span>, intervalo_confianza[<span class="dv">1</span>], <span class="st">","</span>, intervalo_confianza[<span class="dv">2</span>], <span class="st">"]"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Intervalo de confianza: [ 0.0585536807534019 , 0.0983650068357565 ]"</code></pre>
</div>
</div>
<p><strong>Método utilizando una función estadística:</strong></p>
<p>Para un enfoque más directo podemos usar la función <code>prop.test()</code> que está diseñada para pruebas de hipótesis en proporciones, pero también proporciona un intervalo de confianza.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Utilizando prop.test</span></span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(<span class="at">x =</span> num_apartamentos_3_dormitorios, <span class="at">n =</span> num_apartamentos_sol, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener el intervalo de confianza del resultado</span></span>
<span id="cb118-5"><a href="#cb118-5" aria-hidden="true" tabindex="-1"></a>intervalo_confianza <span class="ot">&lt;-</span> test<span class="sc">$</span>conf.int</span>
<span id="cb118-6"><a href="#cb118-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-7"><a href="#cb118-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir resultados</span></span>
<span id="cb118-8"><a href="#cb118-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Probabilidad:"</span>, P))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Probabilidad: 0.0784593437945792"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Intervalo de confianza: ["</span>, intervalo_confianza[<span class="dv">1</span>], <span class="st">","</span>, intervalo_confianza[<span class="dv">2</span>], <span class="st">"]"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Intervalo de confianza: [ 0.0601457117995266 , 0.101530968388163 ]"</code></pre>
</div>
</div>
<p>El método <code>prop.test()</code> es generalmente más recomendable porque maneja internamente varios aspectos del cálculo del intervalo de confianza, incluyendo ajustes para muestras pequeñas. Además, proporciona un resultado más formal y completo que incluye el <code>p-valor</code> de la prueba.</p>
<hr>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>